## Installing Ktrain

In [24]:
!pip install ktrain

## Imports

In [26]:
import tensorflow as tf
import pandas as pd
import numpy as np
import ktrain
from ktrain import text
import tensorflow as tf
from sklearn.metrics import classification_report

## Loading Data

In [28]:
data_train = pd.read_excel('.....',names=["ID","Tweets","Labels"])
data_train.Labels = data_train.Labels.map({'not': 'NOT', 'OFf': 'OFF','NOT': 'NOT', 'OFF': 'OFF'})
data_train.dropna(inplace=True)
data_train.reset_index(drop=True, inplace=True)

data_test = pd.read_csv("....",names=["ID","Tweets","Labels"])
data_test.dropna(inplace=True)
data_test.reset_index(drop=True, inplace=True)

In [29]:
x_train = data_train.Tweets.tolist()
y_train = data_train.Labels.tolist()
x_test = data_test.Tweets.tolist()
y_test = data_test.Labels.tolist()

In [30]:
categories = data_test.Labels.unique()

In [31]:
data_train.Labels.unique()

array(['NOT', 'OFF'], dtype=object)

## Loading the pretrained model

https://huggingface.co/ai4bharat/indic-bert

In [32]:
import ktrain
from ktrain import text
MODEL_NAME = 'ai4bharat/indic-bert'
t = text.Transformer(MODEL_NAME, maxlen=64, class_names=categories)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()


preprocessing train...
language: id
train sequence lengths:
	mean : 18
	95percentile : 37
	99percentile : 43


/usr/local/lib/python3.7/dist-packages/ktrain/utils.py:600: UserWarning: class_names argument was ignored, as they were extracted from string labels in dataset
  if self.get_classes(): warnings.warn('class_names argument was ignored, as they were extracted from string labels in dataset')


Is Multi-Label? False
preprocessing test...
language: id
test sequence lengths:
	mean : 17
	95percentile : 41
	99percentile : 48


404 Client Error: Not Found for url: https://huggingface.co/ai4bharat/indic-bert/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


## Initializing the learner object

In [33]:
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=34)

## Training and validating results

In [34]:
learner.fit_onecycle(8e-5, 1)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 8e-05...
118/118 [==============================] - 72s 497ms/step - loss: 0.6896 - accuracy: 0.5401 - val_loss: 0.6592 - val_accuracy: 0.6649
              precision    recall  f1-score   support

         NOT       0.65      0.69      0.67       465
         OFF       0.68      0.64      0.66       475

    accuracy                           0.66       940
   macro avg       0.67      0.67      0.66       940
weighted avg       0.67      0.66      0.66       940



array([[319, 146],
       [169, 306]])

In [37]:
learner.fit_onecycle(1e-5, 5)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
Epoch 1/5
118/118 [==============================] - 57s 473ms/step - loss: 0.6350 - accuracy: 0.6682 - val_loss: 0.6258 - val_accuracy: 0.6894
Epoch 2/5
118/118 [==============================] - 55s 461ms/step - loss: 0.5809 - accuracy: 0.7254 - val_loss: 0.5855 - val_accuracy: 0.7160
Epoch 3/5
118/118 [==============================] - 56s 465ms/step - loss: 0.4791 - accuracy: 0.7809 - val_loss: 0.5137 - val_accuracy: 0.7606
Epoch 4/5
118/118 [==============================] - 55s 464ms/step - loss: 0.3643 - accuracy: 0.8275 - val_loss: 0.4555 - val_accuracy: 0.7617
Epoch 5/5
118/118 [==============================] - 56s 465ms/step - loss: 0.3125 - accuracy: 0.8495 - val_loss: 0.4525 - val_accuracy: 0.7872
              precision    recall  f1-score   support

         NOT       0.81      0.75      0.78       465
         OFF       0.77      0.82      0.80       475

    accuracy                           0.79       940

array([[349, 116],
       [ 84, 391]])

In [38]:
learner.fit_onecycle(1e-5, 5)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
Epoch 1/5
118/118 [==============================] - 56s 473ms/step - loss: 0.2950 - accuracy: 0.8585 - val_loss: 0.5440 - val_accuracy: 0.7426
Epoch 2/5
118/118 [==============================] - 55s 462ms/step - loss: 0.2992 - accuracy: 0.8622 - val_loss: 0.4756 - val_accuracy: 0.7809
Epoch 3/5
118/118 [==============================] - 56s 465ms/step - loss: 0.2808 - accuracy: 0.8702 - val_loss: 0.4742 - val_accuracy: 0.7766
Epoch 4/5
118/118 [==============================] - 55s 464ms/step - loss: 0.2282 - accuracy: 0.8962 - val_loss: 0.5793 - val_accuracy: 0.7840
Epoch 5/5
118/118 [==============================] - 55s 464ms/step - loss: 0.1685 - accuracy: 0.9290 - val_loss: 0.5800 - val_accuracy: 0.7904
              precision    recall  f1-score   support

         NOT       0.81      0.76      0.78       465
         OFF       0.78      0.82      0.80       475

    accuracy                           0.79       940

array([[353, 112],
       [ 85, 390]])