## Installing Ktrain

In [1]:
!pip install ktrain

## Imports

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import ktrain
from ktrain import text
import tensorflow as tf
from sklearn.metrics import classification_report

## Loading Data

In [3]:
data_train = pd.read_excel('....',names=["ID","Tweets","Labels"])
data_train.Labels = data_train.Labels.map({'not': 'NOT', 'OFf': 'OFF','NOT': 'NOT', 'OFF': 'OFF'})
data_train.dropna(inplace=True)
data_train.reset_index(drop=True, inplace=True)

data_test = pd.read_csv("....",names=["ID","Tweets","Labels"])
data_test.dropna(inplace=True)
data_test.reset_index(drop=True, inplace=True)

In [4]:
x_train = data_train.Tweets.tolist()
y_train = data_train.Labels.tolist()
x_test = data_test.Tweets.tolist()
y_test = data_test.Labels.tolist()

In [5]:
categories = data_test.Labels.unique()

In [6]:
data_train.Labels.unique()

array(['NOT', 'OFF'], dtype=object)

## Loading the pretrained model

https://huggingface.co/ai4bharat/indic-bert

In [7]:
import ktrain
from ktrain import text
MODEL_NAME = 'ai4bharat/indic-bert'
t = text.Transformer(MODEL_NAME, maxlen=40, class_names=categories)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()


preprocessing train...
language: en
train sequence lengths:
	mean : 10
	95percentile : 23
	99percentile : 36


/usr/local/lib/python3.7/dist-packages/ktrain/utils.py:600: UserWarning: class_names argument was ignored, as they were extracted from string labels in dataset
  if self.get_classes(): warnings.warn('class_names argument was ignored, as they were extracted from string labels in dataset')


Is Multi-Label? False
preprocessing test...
language: en
test sequence lengths:
	mean : 11
	95percentile : 20
	99percentile : 26


404 Client Error: Not Found for url: https://huggingface.co/ai4bharat/indic-bert/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


## Initializing the learner object

In [8]:
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=34)

## Training and validating results

In [9]:
learner.fit_onecycle(8e-5, 1)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 8e-05...
118/118 [==============================] - 52s 319ms/step - loss: 0.6928 - accuracy: 0.5131 - val_loss: 0.6928 - val_accuracy: 0.5016
              precision    recall  f1-score   support

         NOT       0.50      0.99      0.66       473
         OFF       0.64      0.02      0.04       478

    accuracy                           0.50       951
   macro avg       0.57      0.50      0.35       951
weighted avg       0.57      0.50      0.35       951



array([[468,   5],
       [469,   9]])

In [10]:
learner.fit_onecycle(1e-5, 4)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
Epoch 1/4
118/118 [==============================] - 37s 305ms/step - loss: 0.6893 - accuracy: 0.5411 - val_loss: 0.6856 - val_accuracy: 0.5499
Epoch 2/4
118/118 [==============================] - 37s 307ms/step - loss: 0.6873 - accuracy: 0.5559 - val_loss: 0.6819 - val_accuracy: 0.5689
Epoch 3/4
118/118 [==============================] - 37s 306ms/step - loss: 0.6824 - accuracy: 0.5731 - val_loss: 0.6737 - val_accuracy: 0.5941
Epoch 4/4
118/118 [==============================] - 37s 306ms/step - loss: 0.6698 - accuracy: 0.5951 - val_loss: 0.6587 - val_accuracy: 0.6151
              precision    recall  f1-score   support

         NOT       0.64      0.53      0.58       473
         OFF       0.60      0.70      0.65       478

    accuracy                           0.62       951
   macro avg       0.62      0.61      0.61       951
weighted avg       0.62      0.62      0.61       951



array([[249, 224],
       [142, 336]])

In [15]:
learner.fit_onecycle(1e-5, 1)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
118/118 [==============================] - 37s 305ms/step - loss: 0.5481 - accuracy: 0.7422 - val_loss: 0.5994 - val_accuracy: 0.6751
              precision    recall  f1-score   support

         NOT       0.66      0.71      0.68       473
         OFF       0.69      0.64      0.67       478

    accuracy                           0.68       951
   macro avg       0.68      0.68      0.67       951
weighted avg       0.68      0.68      0.67       951



array([[334, 139],
       [170, 308]])

In [20]:
learner.fit_onecycle(1e-5, 1)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
118/118 [==============================] - 37s 307ms/step - loss: 0.3862 - accuracy: 0.8380 - val_loss: 0.6402 - val_accuracy: 0.6919
              precision    recall  f1-score   support

         NOT       0.67      0.74      0.70       473
         OFF       0.71      0.65      0.68       478

    accuracy                           0.69       951
   macro avg       0.69      0.69      0.69       951
weighted avg       0.69      0.69      0.69       951



array([[349, 124],
       [169, 309]])

In [22]:
learner.fit_onecycle(1e-5, 1)
learner.validate(class_names=t.get_classes())



begin training using onecycle policy with max lr of 1e-05...
118/118 [==============================] - 37s 305ms/step - loss: 0.3035 - accuracy: 0.8832 - val_loss: 0.7531 - val_accuracy: 0.7056
              precision    recall  f1-score   support

         NOT       0.70      0.72      0.71       473
         OFF       0.71      0.69      0.70       478

    accuracy                           0.71       951
   macro avg       0.71      0.71      0.71       951
weighted avg       0.71      0.71      0.71       951



array([[341, 132],
       [148, 330]])